### ISSUE TITLE
Falsey strings

### ISSUE THREAD

**Issue by estysdesu** [keystroke3/redpaper#1]
https://github.com/keystroke3/redpaper/blob/e16c196d18f8bd0d9e165fa44ff648b7962123c9/menu.py#L49

```
if stay == "x" or "X":
    do_something()
```
is not the same as 
```
if stay == "x" or stay == "X":
    do_something()
```
I recommend trying it out in your REPL to understand why (hint: strings are falsey -- as long as they are not empty, they return True, ie. `if "c":` will return `True`)
I recommend you change it to
```
if stay.lower() == "x":
    do_something()
```
This results in only one check and is clear of your intention.

EDIT: I can see you checked correctly in this [line](https://github.com/keystroke3/redpaper/blob/e16c196d18f8bd0d9e165fa44ff648b7962123c9/menu.py#L89) so maybe you just missed it. Seem to know what you're doing. Nice job on the project.

**Comment by keystroke3** [comment]
So "x" and "X" are both true? What about "x" and "Y"?

**Comment by estysdesu** [comment]
Yeah, it has nothing to do with the characters. What I mean by strings are falsey is if a string is empty, it returns false when checking `if` on **just the variable**. But that's not the same as string comparison which is what you are trying to do I expect. Let me explain a little better.

Case 1: I want to check if a string is empty or not (variable or characters it contains do not matter)
```
def empty_string_checker(s):
    if not s:                                                   # this is equivalent to saying `if s == "":`
        print("String is empty!")
    if s:                                                       # this is equivalent to saying `if s != "":`
        print("String is not empty -- it contains '{}'".format(s))

g = ""
empty_string_checker(g)                                         # --> String is empty!
f = "hiya there"
empty_string_checker(f)                                         # --> String is not empty -- it contains 'hiya there'
```

Case 2: I want to check if a string equals a certain value (aka string comparison)
```
def string_compare(s):
    if s != "hi" or s != "Hi" or s != "HI" or s != "hI":        # this is equivalent to saying `if not s.lower():`
        print("String does not equal 'hi' in any upper or lower case combination")
    if s.lower() == "hi":                                       # instead of checking all the possible case combinations of "hi" we can just check if the lowercase instance (or uppercase) of the variable is equal to the lowercase string we want
        print("String does equal 'hi' and we only had to do one check! -- string: '{}'".format(s))

p = "hello"
string_compare(p)                                               # --> String does not equal 'hi' in any upper or lower case
j = "hI"
string_compare(j)                                               # --> String does equal 'hi' and we only had to do one check! -- string: 'hI'
```
There's no syntax highlighting on the code comments, so [here](https://gist.github.com/estysdesu/a2602a7afd916699eafec213ceba4a12) is the link to a gist -- it might be more helpful to look at that instead.

NOTE: `if stay == "x" or "X":` does not equal `if stay == "x" or stay == "X":` 

This is the original thing I actually started the issue for so i want to make sure that's clear. The first one will always return true because `if "X":` will always return true (falsey strings --> a string is true if not empty). Comparisons in python must always include the variable in each part of it -- so if you want to do two comparisons, you must include the variable in both comparisons. I like to do `if (stay == "x") or (stay == "X"):` to make it clear that I'm doing two comparisons. 

Also, this stuff is pretty easy to check using a REPL (either online ([here](https://repl.it/languages/python3) or [here](https://www.python.org/)) or invoking the python interpreter on your local system (from terminal/command prompt type `python3` (macOS/Linux) or `python` (windows))

**Comment by keystroke3** [comment]
Thanks for the feedback. I saw that that error only occurs with `stay`. I don't know why I did that. With `choice` and all the others, I used the `if choice == "x" or stay == "X"` in other cases. The changes will be updated soon.
