### ISSUE TITLE
Cannot imort colors from utils

### ISSUE THREAD

**Issue by Jabir-Srj** [keystroke3/redpaper#12]
```
fattiejb@lenovo-80x8:~$ redpaper
Traceback (most recent call last):
  File "/usr/bin/redpaper", line 6, in <module>
    from utils import (
ImportError: cannot import name 'colors' from 'utils' (/home/fattiejb/.local/lib/python3.8/site-packages/utils/__init__.py)

```
I am a newbie, I know it says it can't import colors from utils, but how can I resolve it?

**Comment by keystroke3** [comment]
Hello, which method did you use to install redpaper?

**Comment by Jabir-Srj** [comment]
Via the CLI method

**Comment by keystroke3** [comment]
If you are on Arch Linux or Arch based distro with access to the AUR, I would suggest you install it via that method. Make sure you delete the files in `/opt/redpaper-git` and `/usr/bin/redpaper`. If you used the `install.sh` script, then I might have to look into why it is doing that. Also please tell me which version of python you are using and which operating system.

**Comment by keystroke3** [comment]
Closing because it's a stale issue
