### ISSUE TITLE
wall_data.json not found in .redpaper

### ISSUE THREAD

**Issue by mbhatip** [keystroke3/redpaper#7]
Clean install with git, tried running redpaper but wall_data.json does not exist in the .redpaper directory, don't know if its supposed to be made with default settings. OS: Manjaro 18.0.4 w/ KDE & linux 5.2

**Comment by keystroke3** [comment]
Sorry for the late reply, this is a common problem that varies from system to system. I posted a patch but it seems it does not work on all systems. All files in .redpaper folder are supposed to be automatically created. When you started the program, did you download wallpapers first before trying to set? Could you post the contents of `$HOME/.redpaper/settings.ini`? Also, post the error that the terminal gave you.

**Comment by keystroke3** [comment]
I have made an update. Hope it fixes this issue. Reopen this issue if there are any other issues.

**Comment by mbhatip** [comment]
Thank you, it works fine now
