### ISSUE TITLE
How to change Subreddit

### ISSUE THREAD

**Issue by Justinzobel** [keystroke3/redpaper#8]
How do I specify which subreddit to download from?

**Comment by keystroke3** [comment]
I had put this option, but removed it as it seemed nobody was using it. I will add it back.

**Comment by wleoncio** [comment]
Any news on the reimplementation? That's basically the one thing preventing me from dumping Variety in favor of this. :)

**Comment by keystroke3** [comment]
Hello @Justinzobel  @wleoncio,  I finally added the feature. A whole year later :-). You can now set your subreddits of choice from TUI or cli: ```redpaper -sr <sub1> <sub2> <sub3> ...```
Thank you for using the Redpaper. More feedback is welcome.
